[[language]]
name = "yaml"
language-servers = ["yaml-language-server"]

[language-server.yaml-language-server]
command = "yaml-language-server"

[language-server.yaml-language-server.config]
yaml = { schemas = { "minutes.schema.yml" = ["*.minutes.yml"] } }
